/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DailyReport",
  "description": "博客",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://box.kancloud.cn/2015-07-16_55a776534461a.gif",
        "heroText": null,
        "tagline": "日常博客",
        "actionText": "快速访问 →",
        "actionLink": "/blog/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "By CurryChou"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4d5ed008",
      "path": "/"
    },
    {
      "title": "🎉 2021.02.22 今天又是长知识的一天~ 💯",
      "frontmatter": {},
      "regularPath": "/blog/2021/02/23.html",
      "relativePath": "blog/2021/02/23.md",
      "key": "v-253feae8",
      "path": "/blog/2021/02/23.html",
      "headers": [
        {
          "level": 3,
          "title": "🎉 2021.02.22 今天又是长知识的一天~ 💯",
          "slug": "_2021-02-22-今天又是长知识的一天"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/",
      "relativePath": "blog/README.md",
      "key": "v-5bc4f81f",
      "path": "/blog/"
    },
    {
      "title": "git",
      "frontmatter": {},
      "regularPath": "/git/",
      "relativePath": "git/README.md",
      "key": "v-7ab763e3",
      "path": "/git/",
      "headers": [
        {
          "level": 2,
          "title": "git",
          "slug": "git"
        }
      ]
    },
    {
      "title": "css",
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-a50204fe",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "css",
          "slug": "css"
        }
      ]
    },
    {
      "title": "js",
      "frontmatter": {},
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-fec46b82",
      "path": "/js/",
      "headers": [
        {
          "level": 2,
          "title": "js",
          "slug": "js"
        }
      ]
    },
    {
      "title": "guide",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-42fc518f",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "guide",
          "slug": "guide"
        }
      ]
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/vue/",
      "relativePath": "vue/README.md",
      "key": "v-e095ef0a",
      "path": "/vue/",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ]
    },
    {
      "title": "🎉 2021.02.22 今天又是长知识的一天~ 💯",
      "frontmatter": {},
      "regularPath": "/blog/2021/02/22.html",
      "relativePath": "blog/2021/02/22.md",
      "key": "v-677ae4ec",
      "path": "/blog/2021/02/22.html",
      "headers": [
        {
          "level": 3,
          "title": "🎉 2021.02.22 今天又是长知识的一天~ 💯",
          "slug": "_2021-02-22-今天又是长知识的一天"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "Last Updated",
    "logo": "/logo.png",
    "nav": [
      {
        "text": "blog",
        "link": "/blog/"
      },
      {
        "text": "vue",
        "link": "/vue/"
      },
      {
        "text": "css",
        "link": "/css/"
      },
      {
        "text": "js",
        "link": "/js/"
      },
      {
        "text": "github",
        "items": [
          {
            "text": "focus-outside",
            "link": "https://github.com/txs1992/focus-outside"
          },
          {
            "text": "stylus-converter",
            "link": "https://github.com/txs1992/stylus-converter"
          }
        ]
      }
    ],
    "sidebar": {
      "/blog/": [
        {
          "title": "2021年02月",
          "collapsable": false,
          "children": [
            [
              "/blog/2021/02/23",
              "2021年02月23日"
            ],
            [
              "/blog/2021/02/22",
              "2021年02月22日"
            ]
          ]
        },
        {
          "title": "2021年03月",
          "collapsable": false,
          "children": []
        }
      ]
    }
  }
}